services:
  api:
    image: api
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo_database
    environment:
      - ENVIRONMENT=docker-compose_local_container
      - DATABASE_URI=mongodb://mongo_database:27017/
  
  mongo_database:
    image: mongo
    restart: always
    ports: 
      - "27017:27017"