// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	model "github.com/Jeffrey-WEX/ps-tag-onboarding-go/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// IDbRepository is an autogenerated mock type for the IDbRepository type
type IDbRepository struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: newUser
func (_m *IDbRepository) CreateUser(newUser *model.User) (*model.User, error) {
	ret := _m.Called(newUser)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(*model.User) (*model.User, error)); ok {
		return rf(newUser)
	}
	if rf, ok := ret.Get(0).(func(*model.User) *model.User); ok {
		r0 = rf(newUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.User) error); ok {
		r1 = rf(newUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindUserByFirstLastName provides a mock function with given fields: firstName, lastName
func (_m *IDbRepository) FindUserByFirstLastName(firstName string, lastName string) (model.User, error) {
	ret := _m.Called(firstName, lastName)

	if len(ret) == 0 {
		panic("no return value specified for FindUserByFirstLastName")
	}

	var r0 model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (model.User, error)); ok {
		return rf(firstName, lastName)
	}
	if rf, ok := ret.Get(0).(func(string, string) model.User); ok {
		r0 = rf(firstName, lastName)
	} else {
		r0 = ret.Get(0).(model.User)
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(firstName, lastName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserById provides a mock function with given fields: userId
func (_m *IDbRepository) GetUserById(userId string) (*model.User, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.User, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(string) *model.User); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewIDbRepository creates a new instance of IDbRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIDbRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *IDbRepository {
	mock := &IDbRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
