// Code generated by mockery v2.42.1. DO NOT EDIT.

package mocks

import (
	errormessage "github.com/Jeffrey-WEX/ps-tag-onboarding-go/internal/errormessage"
	mock "github.com/stretchr/testify/mock"

	model "github.com/Jeffrey-WEX/ps-tag-onboarding-go/internal/model"
)

// IService is an autogenerated mock type for the IService type
type IService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: newUser
func (_m *IService) CreateUser(newUser *model.User) (*model.User, *errormessage.ErrorMessage) {
	ret := _m.Called(newUser)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *model.User
	var r1 *errormessage.ErrorMessage
	if rf, ok := ret.Get(0).(func(*model.User) (*model.User, *errormessage.ErrorMessage)); ok {
		return rf(newUser)
	}
	if rf, ok := ret.Get(0).(func(*model.User) *model.User); ok {
		r0 = rf(newUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(*model.User) *errormessage.ErrorMessage); ok {
		r1 = rf(newUser)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errormessage.ErrorMessage)
		}
	}

	return r0, r1
}

// GetUserById provides a mock function with given fields: userId
func (_m *IService) GetUserById(userId string) (*model.User, *errormessage.ErrorMessage) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetUserById")
	}

	var r0 *model.User
	var r1 *errormessage.ErrorMessage
	if rf, ok := ret.Get(0).(func(string) (*model.User, *errormessage.ErrorMessage)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(string) *model.User); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *errormessage.ErrorMessage); ok {
		r1 = rf(userId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*errormessage.ErrorMessage)
		}
	}

	return r0, r1
}

// NewIService creates a new instance of IService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IService {
	mock := &IService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
